#: import MeshLinePlot kivy.garden.graph.MeshLinePlot
<Runner>:
	#Handling the gesture event.
	on_two_left_to_right_line:   app.root.transition.direction = 'right'
	on_two_right_to_left_line:  app.root.transition.direction = 'left'
	on_two_down_to_up_line:  app.root.transition.direction = 'up'
	on_two_up_to_down_line:  app.root.transition.direction = 'down'
# Layout the Screen Manager
<NuclearScreenManager>:
	id: manager
	MenuScreen:
		id: menu
		name:'menu'
		manager:manager	
	NuclearControlPanel:
		id: NCP
		name:'ncp'
		manager:manager	

	MyPanel:
		id: panel1
		name:'panel1'
		manager:manager	
	NSRScreen:
		id:nsr
		name:'nsr'
		manager:manager
	ToggleScreen:
		id:toggle
		name:'toggle'
		manager:manager

# Layout the Menu screen
<MenuScreen>:
	#name: 'menu'
	Runner:
		on_two_down_to_up_line:app.root.current =app.root.previous()
	BoxLayout:
		orientation: 'vertical'
		Label:
			text:'Welcome to the Menu!'
			font_size:50
		BoxLayout:
			Button:
				text:'Start'
				font_size:30
				on_release:app.root.current ='nsr'
			Button:
				text:'Exit'
				font_size:30
				on_release:root.stop()
		

# Layout the NCP screen		
<NuclearControlPanel>:

	#name: 'ncp'

	FloatLayout:
		BoxLayout:
			orientation:'vertical'

			GridLayout:
				cols: 4
				rows: 1
				spacing: 70, 40 
			##################################################################Light Line#######################################################################
				Light_indicator:	
					id:warning1
					num:3
					color1:'green'
					color2:'yellow'
					color3:'red'
					setting_on: False
					pos_l1: [25,100]
					pos_l2: [100,100]
					pos_l3: [175,100]
					label_on: True
					l1_label:"On"
					l2_label: "Warning"
					l3_label: "Danger"
				Light_indicator:	
					id:warning2
					num:3
					color1:'green'
					color2:'yellow'
					color3:'red'
					setting_on: False
					pos_l1: [25,100]
					pos_l2: [100,100]
					pos_l3: [175,100]
				Light_indicator:	
					id:warning3
					num:3
					color1:'green'
					color2:'yellow'
					color3:'red'
					setting_on: False
					pos_l1: [25,100]
					pos_l2: [100,100]
					pos_l3: [175,100]
				Light_indicator:
					num:3	
					id:warning4
					color1:'green'
					color2:'yellow'
					color3:'red'
					setting_on: False
					pos_l1: [25,100]
					pos_l2: [100,100]
					pos_l3: [175,100]

			GridLayout:
				cols: 4
				rows: 1
				spacing: 70, 40 




	

			##################################################################Gauge Line###########################################################
				Gauges:
					id: gauge1
					value:knob1.value
					gauge_type:'half'
				Gauges:
					id: gauge2
					value:knob2.value
					gauge_type:'half'

				Gauges:
					id: gauge3
					value:knob3.value
					gauge_type:'half'
				Gauges:
					id: gauge4
					value:knob4.value
					gauge_type:'half'
			##################################################################Knob Line###########################################################
			GridLayout:
				center:
				cols: 4
				rows: 1
				spacing: 300, 40 
						
				Knob:
					id: knob1
					size:150,150
					value: 0
					min: 0
					max: 100
					step: 1
					knobimg_source: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/knob_metal.png"
					knobimg_size: 1
					show_label: False
					show_marker: False

				Knob:
					id: knob2
					size: 150,150
					value: 0
					min: 0
					max: 100
					step: 1
					knobimg_source: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/knob_metal.png"
					knobimg_size: 1
					show_label: False
					show_marker: False
				Knob:
					id: knob3
					size:150,150
					value: 0
					min: 0
					max: 100
					step: 1
					knobimg_source: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/knob_metal.png"
					knobimg_size: 0.9
					show_label: False
					show_marker: False
				Knob:
					id: knob4
					size:150,150
					value: 0
					min: 0
					max: 100
					step: 1
					knobimg_source: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/knob_metal.png"
					knobimg_size: 0.9
					show_label: False
					show_marker: False

			##################################################################Label Line###########################################################
			GridLayout:
				cols: 4
				rows: 1
				spacing: 70, 40 
				Label:
					id: PowerLabel
					text:'Power'
					font_size:30



				Label:
					id: RaiseLabel
					text:'Raise'
					font_size:30
				Label:
					id: LowerLabel
					text:'Lower'
					font_size:30
				Label:
					id: TurboLabel
					text:'Turbo'
					font_size:30

			##################################################################Slider Line###########################################################
#			GridLayout:
#				cols: 4
#				rows: 1
#				spacing: 70, 40 
#				Slider:
#					orientation:'vertical'
#					max: 1
#					min:0
#					value:1
#					cursor_size:[1,0.1]
#				Slider:
#					orientation:'vertical'
#					max: 1
#					min:0
#					value:1
#				Slider:
#					orientation:'vertical'
#					max: 1
#					min:0
#					value:1
#				Slider:
#					orientation:'vertical'
#					max: 1
#					min:0
#					value:1


			BoxLayout:

				Button:
					id: Stop_button
					size_hint:1,1
					text: 'Scram!!!'
					font_size: 30
					on_press:root.stop()
					pos: 900,0
					canvas:
						Color:
							rgba: 1, 0, 0, 0.5
						Rectangle:
							size: self.size
							pos: self.pos
				Button:
					id:menubuttonnuke
					size_hint:1,1
					text: 'Menu'
					font_size: 30
					on_release: app.root.current ='menu'



	Runner: 
		on_two_up_to_down_line: app.root.current = 'menu'
		on_two_left_to_right_line: app.root.current = 'panel1'



	

<MyPanel>:
	#name:'panel1'
	Runner: 
		on_two_up_to_down_line: app.root.current = 'menu'
		on_two_right_to_left_line: app.root.current = 'ncp'
		on_two_left_to_right_line: app.root.current = 'nsr'
	BoxLayout:
		orientation:'vertical'
		BoxLayout:
			Gauges:
				id: gauge1
				value:knob.value
				gauge_type:'60'
				size_gauge:256
			
			Light_indicator:	
				id:warning1
				orientation: 'vertical'
				size_lights: [30,30]
				num:3
				color1:'green'
				color2:'yellow'
				color3:'red'
				setting_on: False
				pos_l1: [100,175]
				pos_l2: [100,100]
				pos_l3: [100,25]
				label_on: True
				l1_label:"On"
				l2_label: "Warning"
				l3_label: "Danger"
			Gauges:
				id: gauge2
				value:knob.value
				gauge_type:'3/4'
				size_gauge:256
	


			Knob:
				id: knob
				size:150,150
				value: 0
				min: 0
				max: 100
				step: 1
				knobimg_source: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/knob_metal.png"
				knobimg_size: 0.9
				show_label: False
				show_marker: False

			Gauges:
				id: gauge3
				value:knob.value #value:root.manager.NCP.knob1.value
				gauge_type:'60'
				size_gauge:256

		BoxLayout:
			Gauges:
				id: gauge4
				value:knob2.value
				gauge_type:'60'
				size_gauge:256
			
			Light_indicator:	
				id:warning2
				orientation: 'vertical'
				size_lights: [30,30]
				num:3
				color1:'green'
				color2:'yellow'
				color3:'red'
				setting_on: False
				pos_l1: [100,175]
				pos_l2: [100,100]
				pos_l3: [100,25]
				label_on: True
				l1_label:"On"
				l2_label: "Warning"
				l3_label: "Danger"
			Gauges:
				id: gauge5
				value:knob2.value
				gauge_type:'3/4'
				size_gauge:256
	


			Knob:
				id: knob2
				size:150,150
				value: 0
				min: 0
				max: 100
				step: 1
				knobimg_source: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/knob_metal.png"
				knobimg_size: 0.9
				show_label: False
				show_marker: False

			Gauges:
				id: gauge6
				value:knob2.value
				gauge_type:'60'
				size_gauge:256


<NSRScreen>:
	Runner: 
		on_two_down_to_up_line: app.root.current = 'toggle'
		on_two_up_to_down_line: app.root.current = 'menu'
		on_two_right_to_left_line: app.root.current = 'panel1'
		
	BoxLayout:
		BoxLayout:
			size_hint: 0.5,1
			orientation:'vertical'
			BoxLayout:
				orientation:'vertical'
				Light_indicator:
					id:TL_LI_R1
					orientation: 'horizontal'
					num:2
					color1:'white'
					color2: 'red'
					pos_l1:[50,100]
					pos_l2:[150,100]
					label_on:True
					l1_label:'On'
					l2_label:'off'
					bol1:True
					setting_on:False
				Light_indicator:
					id:TL_LI_R2
					orientation: 'horizontal'
					num:2
					color1:'green'
					color2: 'red'
					pos_l1:[50,100]
					pos_l2:[150,100]
					label_on:False
					bol1:True
					setting_on:False
			Light_indicator:
				id:ML_LI_R2
				orientation: 'vertical'
				num:3
				color1:'green'
				color2:'yellow'
				color3:'red'
				pos_l1:[100,175]
				pos_l2:[100,100]
				pos_l3:[100,25]
				label_on:False
				bol1:True
				setting_on:False
			Label:
				text: 'speaker'
				font_size:20

		BoxLayout:
			size_hint:.5,1
			orientation:'vertical'
			GridLayout:
				cols:2
				rows:2
				spacing: 50, 20
				pos_hint: {'center_x':0.5, 'center_y':0.25}
				
				
				ToggleButton:
					size_hint:None, None
					size: 100,100
					text:'Button 1'
					group:'group1'
					canvas:
						Color:
							rgba: 1, 0, 0, 0.5
						Rectangle:
							size: self.size
							pos: self.pos


				ToggleButton:
					size_hint:None, None
					size: 100,100
					text:'Button 2'
					group:'group1'
					state:'down'
					canvas:
						Color:
							rgba: 1, 0, 0, 0.5
						Rectangle:
							size: self.size
							pos: self.pos
			
				ToggleButton:
					size_hint:None, None
					size: 100,100
					text:'Button 3'
					group:'group1'
					canvas:
						Color:
							rgba: 1, 0, 0, 0.5
						Rectangle:
							size: self.size
							pos: self.pos
				ToggleButton:
					size_hint:None, None
					size: 100,100
					text:'Button 4'
					group:'group1'
					canvas:
						Color:
							rgba: 1, 0, 0, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

			GridLayout:
				cols:2
				rows:2
				spacing: 50, 20
				pos_hint: {'center_x':0.5, 'center_y':0.25}

				ToggleButton:
					size_hint:None, None
					size: 100,100
					text:'Button 5'
					group:'group2'
					canvas:
						Color:
							rgba: 0, 1, 0, 0.5
						Rectangle:
							size: self.size
							pos: self.pos
				ToggleButton:
					size_hint:None, None
					size: 100,100
					text:'Button 6'
					group:'group2'
					canvas:
						Color:
							rgba: 0, 1, 0, 0.5
						Rectangle:
							size: self.size
							pos: self.pos
			
				ToggleButton:
					size_hint:None, None
					size: 100,100
					text:'Button 7'
					group:'group2'
					canvas:
						Color:
							rgba: 0, 1, 0, 0.5
						Rectangle:
							size: self.size
							pos: self.pos
				ToggleButton:
					size_hint:None, None
					size: 100,100
					text:'Button 8'
					group:'group2'
					state: 'down'
					canvas:
						Color:
							rgba: 0, 1, 0, 0.5
						Rectangle:
							size: self.size
							pos: self.pos
			GridLayout:
				cols:1
				rows:3
				spacing: 50, 20
				pos_hint: {'center_x':0.75, 'center_y':0.25}
				ToggleButton:
					size_hint:None, None
					size: 100,100
					text:'Button 9'
					group:'group3'
					canvas:
						Color:
							rgba: 1, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos
				ToggleButton:
					size_hint:None, None
					size: 100,100
					text:'Button 10'
					group:'group3'
					state: 'down'
					canvas:
						Color:
							rgba: 1, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos
				ToggleButton:
					size_hint:None, None
					size: 100,100
					text:'Button 11'
					group:'group3'
					canvas:
						Color:
							rgba: 1, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos




		BoxLayout:
			orientation: 'vertical'
			size_hint: 1.5,1
			Button:
				text: 'BIG'	
		BoxLayout:
			size_hint: .5,1
			orientation: 'vertical'
			BoxLayout:
				Label:
					text:""
			BoxLayout:
				orientation:'vertical'
				Label:
					text: 'Key'
					font_size: 20
				Light_indicator:
					num:1
					pos_l1: 130,40
					color1:'white'
					setting_on: False
					label_on:False
				Label:
					text:""
			GridLayout:
				cols:2
				rows:2
				spacing: 50, 60
				pos_hint: {'center_x':0.6, 'center_y':0.25}
				ToggleButton:
					size_hint:None, None
					size: 100,100
					text:'Button 12'
					group:'group4'
					canvas:
						Color:
							rgba: 1, 0, 0, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size: 100,100
					text:'Button 13'
					group:'group4'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos
			
				ToggleButton:
					size_hint:None, None
					size: 100,100
					text:'Button 14'
					group:'group5'
					canvas:
						Color:
							rgba: 1, 0, 0, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size: 100,100
					text:'Button 15'
					group:'group5'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos



<ToggleScreen>:
	Runner: 
		on_two_up_to_down_line: app.root.current = 'nsr'
#		on_two_left_to_right_line: app.root.current = 'nsr'
	
	BoxLayout:
		BoxLayout:
			size_hint: 0.25,1
			orientation: 'vertical'
			Light_indicator:
				num:3
				orientation: 'horizontal'
				color1:'green'
				color2: 'green'
				color3:'green'
				pos_l1:[25/2,100]
				pos_l2:[100/2,100]
				pos_l3:[175/2,100]
				label_on:False
				bol1:True
				bol2:True
				bol3:True
				setting_on:False
				size_lights:25,25
			Light_indicator:
				num:1
				orientation: 'horizontal'
				color1:'green'
				pos_l1:[100/2,175]
				label_on:False
				bol1:True
				setting_on:False
				size_lights:25,25
			Label:
				text:""
			Label:
				text:""
			Label:
				text:""
			Label:
				text:""


		BoxLayout:
			size_hint: 0.5,1
			orientation:'vertical'
			GridLayout:
				rows:3
				cols:3
				spacing: 50, 60
				pos_hint: {'center_x':0.6, 'center_y':0.25}
				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group1'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos
				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group1'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos
				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group1'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos
				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group1'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos
				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group1'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos
				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group1'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos
				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group1'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos
				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group1'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos
				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group1'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos



			GridLayout:
				rows:1
				cols:3
				spacing: 50, 60
				pos_hint: {'center_x':0.6, 'center_y':0.25}
				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group2'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos
				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group2'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos
				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group2'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				
				

		BoxLayout:
			orientation: 'vertical'
			GridLayout:
				rows:5
				cols:8
				spacing: 25, 30
				pos_hint: {'center_x':0.6, 'center_y':0.25}
				
				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos


			
				Label:
					text:""

				Label: 
					text: ""
				Label:
					text:""

				Label: 
					text:""
				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos
			BoxLayout:
				GridLayout:
					rows:1
					cols:3
					spacing: 25, 30
					#size_hint: None, None
					pos_hint: {'center_x':1, 'center_y':-0.0}
#					canvas:
#						Color:
#							rgba: 0,1,0,0.25
#						Rectangle:
#							size: self.size
#							pos: self.pos			
					ToggleButton:
						size_hint:None, None
						size:50,50
						text:'Button'
						group:'group4'
						canvas:
							Color:
								rgba: 0, 0, 1, 0.5
							Rectangle:
								size: self.size
								pos: self.pos
					ToggleButton:
						size_hint:None, None
						size:50,50
						text:'Button'
						group:'group4'
						canvas:
							Color:
								rgba: 0, 0, 1, 0.5
							Rectangle:
								size: self.size
								pos: self.pos
					ToggleButton:
						size_hint:None, None
						size:50,50
						text:'Button'
						group:'group4'
						canvas:
							Color:
								rgba: 0, 0, 1, 0.5
							Rectangle:
								size: self.size
								pos: self.pos
				GridLayout:
					rows:1
					cols:3
					spacing: 25, 30
					pos_hint: {'center_x':1, 'center_y':-0.0}
#					canvas:
#						Color:
#							rgba: 1,0,0,0.25
#						Rectangle:
#							size: self.size
#							pos: self.pos			
					ToggleButton:
						size_hint:None, None
						size:50,50
						text:'Button'
						group:'group4'
						canvas:
							Color:
								rgba: 0, 0, 1, 0.5
							Rectangle:
								size: self.size
								pos: self.pos
					ToggleButton:
						size_hint:None, None
						size:50,50
						text:'Button'
						group:'group4'
						canvas:
							Color:
								rgba: 0, 0, 1, 0.5
							Rectangle:
								size: self.size
								pos: self.pos
					ToggleButton:
						size_hint:None, None
						size:50,50
						text:'Button'
						group:'group4'
						canvas:
							Color:
								rgba: 0, 0, 1, 0.5
							Rectangle:
								size: self.size
								pos: self.pos
			BoxLayout:
				
				
				canvas:
					Color:
						rgba: 0.5,0.5,0.5,0.5
					Rectangle:
						size:200,200
						pos: 250,0

					Rectangle:
						size:200,200
						pos: 600,0

					Rectangle:
						size:200,200
						pos: 1050,0

					Rectangle:
						size:200,200
						pos: 1300,0


		BoxLayout:
			orientation: 'vertical'
			GridLayout:
				rows:5
				cols:8
				spacing: 25, 30
				pos_hint: {'center_x':0.6, 'center_y':0.25}
				
				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos
				ToggleButton:
					size_hint:None, None
					size:50,50
					text:'Button'
					group:'group3'
					canvas:
						Color:
							rgba: 0, 0, 1, 0.5
						Rectangle:
							size: self.size
							pos: self.pos

			BoxLayout:
				GridLayout:
					rows:1
					cols:3
					spacing: 25, 30
					#size_hint: None, None
					pos_hint: {'center_x':0.7, 'center_y':0.5}
#					canvas:
#						Color:
#							rgba: 0,1,0,0.25
#						Rectangle:
#							size: self.size
#							pos: self.pos			
					ToggleButton:
						size_hint:None, None
						size:50,50
						text:'Button'
						group:'group4'
						canvas:
							Color:
								rgba: 0, 0, 1, 0.5
							Rectangle:
								size: self.size
								pos: self.pos
					ToggleButton:
						size_hint:None, None
						size:50,50
						text:'Button'
						group:'group4'
						canvas:
							Color:
								rgba: 0, 0, 1, 0.5
							Rectangle:
								size: self.size
								pos: self.pos
					ToggleButton:
						size_hint:None, None
						size:50,50
						text:'Button'
						group:'group4'
						canvas:
							Color:
								rgba: 0, 0, 1, 0.5
							Rectangle:
								size: self.size
								pos: self.pos
				BoxLayout:
					orientation:'vertical'
					
					GridLayout:
						rows:2
						cols:3
						spacing: 25, 30
						size_hint: None, 0.5
						pos_hint: {'center_x':0.4, 'center_y':1}
	#					canvas:
	#						Color:
	#							rgba: 0,1,0,0.25
	#						Rectangle:
	#							size: self.size
	#							pos: self.pos			
						ToggleButton:
							size_hint:None, None
							size:50,50
							text:'Button'
							group:'group5'
							canvas:
								Color:
									rgba: 0, 0, 1, 0.5
								Rectangle:
									size: self.size
									pos: self.pos
						ToggleButton:
							size_hint:None, None
							size:50,50
							text:'Button'
							group:'group5'
							canvas:
								Color:
									rgba: 0, 0, 1, 0.5
								Rectangle:
									size: self.size
									pos: self.pos
						ToggleButton:
							size_hint:None, None
							size:50,50
							text:'Button'
							group:'group5'
							canvas:
								Color:
									rgba: 0, 0, 1, 0.5
								Rectangle:
									size: self.size
									pos: self.pos

						ToggleButton:
							size_hint:None, None
							size:50,50
							text:'Button'
							group:'group5'
							canvas:
								Color:
									rgba: 0, 0, 1, 0.5
								Rectangle:
									size: self.size
									pos: self.pos
						ToggleButton:
							size_hint:None, None
							size:50,50
							text:'Button'
							group:'group5'
							canvas:
								Color:
									rgba: 0, 0, 1, 0.5
								Rectangle:
									size: self.size
									pos: self.pos
						ToggleButton:
							size_hint:None, None
							size:50,50
							text:'Button'
							group:'group5'
							canvas:
								Color:
									rgba: 0, 0, 1, 0.5
								Rectangle:
									size: self.size
									pos: self.pos


					GridLayout:
						rows:2
						cols:3
						spacing: 25, 30
						size_hint: None, 0.5
						pos_hint: {'center_x':0.4, 'center_y':-0.3}
	#					canvas:
	#						Color:
	#							rgba: 0,1,0,0.25
	#						Rectangle:
	#							size: self.size
	#							pos: self.pos			
						ToggleButton:
							size_hint:None, None
							size:50,50
							text:'Button'
							group:'group5'
							canvas:
								Color:
									rgba: 0, 0, 1, 0.5
								Rectangle:
									size: self.size
									pos: self.pos
						ToggleButton:
							size_hint:None, None
							size:50,50
							text:'Button'
							group:'group5'
							canvas:
								Color:
									rgba: 0, 0, 1, 0.5
								Rectangle:
									size: self.size
									pos: self.pos
						ToggleButton:
							size_hint:None, None
							size:50,50
							text:'Button'
							group:'group5'
							canvas:
								Color:
									rgba: 0, 0, 1, 0.5
								Rectangle:
									size: self.size
									pos: self.pos

						ToggleButton:
							size_hint:None, None
							size:50,50
							text:'Button'
							group:'group5'
							canvas:
								Color:
									rgba: 0, 0, 1, 0.5
								Rectangle:
									size: self.size
									pos: self.pos
						ToggleButton:
							size_hint:None, None
							size:50,50
							text:'Button'
							group:'group5'
							canvas:
								Color:
									rgba: 0, 0, 1, 0.5
								Rectangle:
									size: self.size
									pos: self.pos
						ToggleButton:
							size_hint:None, None
							size:50,50
							text:'Button'
							group:'group5'
							canvas:
								Color:
									rgba: 0, 0, 1, 0.5
								Rectangle:
									size: self.size
									pos: self.pos
