#: import MeshLinePlot kivy.garden.graph.MeshLinePlot

<NuclearScreenManager>:
	MenuScreen:	
	NCPScreen:
	KnobScreen:


<MenuScreen>:
	name: 'menu'
	BoxLayout:
		orientation: 'vertical'
		Label:
			text:'Welcome to the Menu!'
			font_size:50
		BoxLayout:
			Button:
				text:'Nuclear Control Panel'
				font_size:30
				on_release:app.root.current ='ncp'
			Button:
				text:'Knob Panel'
				font_size:30
				on_release:app.root.current ='knob'

<NuclearControlPanel>:
	orientation: 'vertical'	


	BoxLayout: 
		size_hint:[1,3]
		orientation:'horizontal'
	#		canvas:
	#			Color:
	#				rgba: 1, 1, 0, 0.5
	#			Rectangle:
	#				size: self.size
	#				pos: self.pos

		GridLayout:
			cols: 4
			rows: 4
			spacing: 70, 0 
	#			canvas:
	#				Color:
	#					rgba: 1, 0, 1, 0.5
	#				Rectangle:
	#					size: self.size
	#					pos: self.pos


##################################################################Gauge Line###########################################################
			Gauge:
				id: gauge1
				value:knob1.value
				max: 50
	
			Gauge:
				id: gauge2

				value:knob2.value

			Gauge:
				id: gauge3
				value:knob3.value

			Gauge:
				id: gauge4
				value:knob4.value
##################################################################Knob Line###########################################################			
			Knob:
				id: knob1
				size: 100, 100
				value: 0
				min: 0
				max: 100
				step: 1
				knobimg_source: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/knob_metal.png"
				knobimg_size: 0.9
				show_label: False
				show_marker: True
			Knob:
				id: knob2
				size: 100, 100
				value: 0
				min: 0
				max: 100
				step: 1
				knobimg_source: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/knob_metal.png"
				knobimg_size: 0.9
				show_label: False
				show_marker: True
			Knob:
				id: knob3
				size: 100, 100
				value: 0
				min: 0
				max: 100
				step: 1
				knobimg_source: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/knob_metal.png"
				knobimg_size: 0.9
				show_label: False
				show_marker: True
			Knob:
				id: knob4
				size: 100, 100
				value: 0
				min: 0
				max: 100
				step: 1
				knobimg_source: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/knob_metal.png"
				knobimg_size: 0.9
				show_label: False
				show_marker: True
##################################################################Label Line###########################################################
			Label:
				id: PowerLabel
				text:'Power'
				font_size:30



			Label:
				id: RaiseLabel
				text:'Raise'
				font_size:30
			Label:
				id: LowerLabel
				text:'Lower'
				font_size:30
			Label:
				id: TurboLabel
				text:'Turbo'
				font_size:30
##################################################################Slider Line###########################################################
			Slider:
				orientation:'vertical'
				max: 1
				min:0
				value:1
			Slider:
				orientation:'vertical'
				max: 1
				min:0
				value:1
			Slider:
				orientation:'vertical'
				max: 1
				min:0
				value:1
			Slider:
				orientation:'vertical'
				max: 1
				min:0
				value:1


		

	BoxLayout:
		Label:
			text:''

	#			canvas:
	#				Color:
	#					rgba: 0, 0, 1, 0.5
	#				Rectangle:
	#					size: self.size
	#					pos: self.pos



		Button:
			id: Stop_button
			size_hint:[0.5, 0.5]
			text: 'Scram!!!'
			font_size: 30
			on_press:root.stop()
			canvas:
				Color:
					rgba: 1, 0, 0, 0.5
				Rectangle:
					size: self.size
					pos: self.pos
		Button:
			id:menubuttonnuke
			size_hint:[0.5, 0.5]
			text: 'Menu'
			font_size: 30
			on_release: app.root.current ='menu'


<NCPScreen>:
	name: 'ncp'
	NuclearControlPanel:
<KnobScreen>:
	name: 'knob'
	BoxLayout:
		orientation: 'vertical'

		Gauge: 
			value: knob1.value
		BoxLayout:
			Knob:
				id: knob1
				size: 100, 100
				value: 1
				min: 1
				max: 11
				step: 1
				knobimg_source: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/knob_metal.png"
				knobimg_size: 0.9
				show_label: True
				show_marker: True
				on_touch_move: root.change_knob()
			Label:
				id:label
				text: str(knob1.value-1)
		BoxLayout:

			Button:
				id: Start_button
				size_hint:[0.1, 1]
				text: 'Start!!!'
				font_size: 30
				on_press:root.start()

				canvas:
					Color:
						rgba: 0, 1, 0, 0.5
					Rectangle:
						size: self.size
						pos: self.pos
			Button:
				id: Stop_button
				size_hint:[0.1, 1]
				text: 'SCRAM!!!'
				font_size: 30
				on_press:root.stop()

				canvas:
					Color:
						rgba: 1, 0, 0, 0.5
					Rectangle:
						size: self.size
						pos: self.pos
			Button:
				id:menubuttonknob
				size_hint:[0.1, 1]
				text: 'Menu'
				font_size: 30
				on_release: app.root.current ='menu'


