#: import MeshLinePlot kivy.garden.graph.MeshLinePlot

<NuclearScreenManager>:
	MenuScreen:	
	NCPScreen:
	KnobScreen:


<MenuScreen>:
	name: 'menu'
	BoxLayout:
		orientation: 'vertical'
		Label:
			text:'Welcome to the Menu!'
			font_size:50
		BoxLayout:
			Button:
				text:'Nuclear Control Panel'
				font_size:30
				on_release:app.root.current ='ncp'
			Button:
				text:'Knob Panel'
				font_size:30
				on_release:app.root.current ='knob'

<NuclearControlPanel>:
	

	orientation: 'vertical'
	BoxLayout:
		Graph: 
			id: my_plot
			xlabel: "Time (s)"
			ylabel: "Level"
			ymax:1.5
			ymin: -1.5
			
		Graph: 
			id:my_real_plot
			xlabel: "Time (s)"
			ylabel: "Rate"
			ymax:1.5
			ymin: -1.5

	BoxLayout: 
		size_hint:[1,3]
		orientation:'horizontal'
	#		canvas:
	#			Color:
	#				rgba: 1, 1, 0, 0.5
	#			Rectangle:
	#				size: self.size
	#				pos: self.pos

		GridLayout:
			cols: 3
			rows: 4
			spacing: 0, 70 
	#			canvas:
	#				Color:
	#					rgba: 1, 0, 1, 0.5
	#				Rectangle:
	#					size: self.size
	#					pos: self.pos
			Label:
				id: PowerLabel
				text:'Power'
				font_size:30
			Slider:
				orientation:'vertical'
				max: 1
				min:0
				value:1
			Knob:
				size: 100, 100
				value: 0
				min: 0
				max: 100
				step: 1
				knobimg_source: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/knob_metal.png"
				knobimg_size: 0.9
				show_label: False
				show_marker: True

			Label:
				id: RaiseLabel
				text:'Raise'
				font_size:30
			Switch:

			Knob:
				size: 100, 100
				value: 0
				knobimg_source: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/knob_black.png"
				markeroff_color: 0.0, 0.0, .0, 1
				knobimg_size: 0.9
				marker_img: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/bline3.png"
				min: 0
				max: 100

			Label:
				id: LowerLabel
				text:'Lower'
				font_size:30
			Switch:


			Knob:
				size: 100, 100
				value: 0
				knobimg_source: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/knob_black.png"
				markeroff_color: 0.0, 0.0, .0, 1
				knobimg_size: 0.9
				marker_img: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/bline3.png"	

			Label:
				id: TurboLabel
				text:'Turbo'
				font_size:30
			Switch:


			Knob:
				size: 100, 100
				value: 0
				knobimg_source: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/knob_black.png"
				markeroff_color: 0.0, 0.0, .0, 1
				knobimg_size: 0.9
				marker_img: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/bline3.png"	


		GridLayout:
			cols: 3
			rows: 4
	#			spacing: 0,70
			Button:
				id: my_buton1
				text: '1'
				font_size: 30
	

			Button:
				id: my_button2
				text: '2'
				font_size: 30



			Button:
				id: my_button3
				text: '3'
				font_size: 30


			Button:
				id: my_button4
				text: '4'
				font_size: 30


			Button:
				id: my_button5
				text: '5'
				font_size: 30
	#				canvas:
	#					Color:
	#						rgba: 0, 1, 0, 0.5
	#					Rectangle:
	#						size: self.size
	#						pos: self.pos

			Button:
				id: my_button6
				text: '6'
				font_size: 30


			Button:
				id: my_button7
				text: '7'
				font_size: 30


			Button:
				id: my_button8
				text: '8'
				font_size: 30


			Button:
				id: my_button9
				text: '9'
				font_size: 30


			Button:
				id: my_buttonstar
				text: '*'
				font_size: 30


			Button:
				id: my_button0
				text: '0'
				font_size: 30


			Button:
				id: my_buttonlbs
				text: '#'
				font_size: 30


	BoxLayout:
		Label:
			text:''

	#			canvas:
	#				Color:
	#					rgba: 0, 0, 1, 0.5
	#				Rectangle:
	#					size: self.size
	#					pos: self.pos



		Button:
			id: Stop_button
			size_hint:[0.5, 0.5]
			text: 'Stop!!!'
			font_size: 30

			canvas:
				Color:
					rgba: 1, 0, 0, 0.5
				Rectangle:
					size: self.size
					pos: self.pos
		Button:
			id:menubuttonnuke
			size_hint:[0.5, 0.5]
			text: 'Menu'
			font_size: 30
			on_release: app.root.current ='menu'


<NCPScreen>:
	name: 'ncp'
	NuclearControlPanel:
<KnobScreen>:
	name: 'knob'
	BoxLayout:
		orientation: 'vertical'

		Graph: 
			id: my_plot
			xlabel: "Time (s)"
			ylabel: "Level"
			ymax:15
			ymin: -10
		BoxLayout:
			Knob:
				id: knob1
				size: 100, 100
				value: 1
				min: 1
				max: 11
				step: 1
				knobimg_source: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/knob_metal.png"
				knobimg_size: 0.9
				show_label: True
				show_marker: True
				on_touch_move: root.change_knob()
			Label:
				id:label
				text: str(knob1.value-1)
		BoxLayout:

			Button:
				id: Start_button
				size_hint:[0.1, 1]
				text: 'Start!!!'
				font_size: 30
				on_press:root.start()

				canvas:
					Color:
						rgba: 0, 1, 0, 0.5
					Rectangle:
						size: self.size
						pos: self.pos
			Button:
				id: Stop_button
				size_hint:[0.1, 1]
				text: 'SCRAM!!!'
				font_size: 30
				on_press:root.stop()

				canvas:
					Color:
						rgba: 1, 0, 0, 0.5
					Rectangle:
						size: self.size
						pos: self.pos
			Button:
				id:menubuttonknob
				size_hint:[0.1, 1]
				text: 'Menu'
				font_size: 30
				on_release: app.root.current ='menu'


