<NuclearControlPanel>:
	orientation: 'vertical'
	TextInput:
		size_hint_y: None
		font_size: 30
	BoxLayout: 
		orientation:'horizontal'

		GridLayout:
			cols: 3
			rows: 4
			spacing: 0, 70 

			Label:
				id: PowerLabel
				text:'Power'
				font_size:30
			Switch:
			
			Knob:
				size: 150, 150
				value: 0
				knobimg_source: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/knob_black.png"
				markeroff_color: 0.0, 0.0, .0, 1
				knobimg_size: 0.9
				marker_img: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/bline3.png"
			
			Label:
				id: RaiseLabel
				text:'Raise'
				font_size:30
			Switch:
			
			Knob:
				size: 150, 150
				value: 0
				knobimg_source: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/knob_black.png"
				markeroff_color: 0.0, 0.0, .0, 1
				knobimg_size: 0.9
				marker_img: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/bline3.png"
				min: 0
				max: 100

			Label:
				id: LowerLabel
				text:'Lower'
				font_size:30
			Switch:

			
			Knob:
				size: 150, 150
				value: 0
				knobimg_source: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/knob_black.png"
				markeroff_color: 0.0, 0.0, .0, 1
				knobimg_size: 0.9
				marker_img: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/bline3.png"	

			Label:
				id: TurboLabel
				text:'Turbo'
				font_size:30
			Switch:
	
			
			Knob:
				size: 150, 150
				value: 0
				knobimg_source: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/knob_black.png"
				markeroff_color: 0.0, 0.0, .0, 1
				knobimg_size: 0.9
				marker_img: "/usr/lib/python2.7/dist-packages/kivy/garden/knob/img/bline3.png"	
		GridLayout:
			cols: 3
			rows: 4

			Button:
				id: my_switch1
				text: '1'
				font_size: 30
				
	
			Button:
				id: my_button2
				text: '2'
				font_size: 30
			


			Button:
				id: my_button3
				text: '3'
				font_size: 30
			

			Button:
				id: my_button4
				text: '4'
				font_size: 30
			

			Button:
				id: my_button5
				text: '5'
				font_size: 30
				canvas:
					Color:
						rgba: 0, 1, 0, 0.5
					Rectangle:
						size: self.size
						pos: self.pos
	
			Button:
				id: my_button6
				text: '6'
				font_size: 30
			

			Button:
				id: my_button7
				text: '7'
				font_size: 30
			

			Button:
				id: my_button8
				text: '8'
				font_size: 30
			

			Button:
				id: my_button9
				text: '9'
				font_size: 30
			

			Button:
				id: my_buttonstar
				text: '*'
				font_size: 30
			

			Button:
				id: my_button0
				text: '0'
				font_size: 30
			

			Button:
				id: my_buttonlbs
				text: '#'
				font_size: 30
